### ISSUE TITLE
Read the Docs integration

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/django-defender#139]
As indicated in #121 and #138 a Read the Docs page and integration would be nice for the repository. Initial integration can be done with [`sphinx-quickstart`](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html).

@kencochrane is probably the best person for creating the initial Read the Docs page as the maintainer, and adding the Jazzband bot into the project, and after that we can set up the documentation pipeline and webhooks.

The project can be imported into RTD here (manual import probably works best): 

https://readthedocs.org/dashboard/import/

The docs need a version tag that is tied to the repository as well as a Python version set up. It would probably be nice to set the documentation target up as Python 3, as the official Python 2.7 deprecation is coming up in just a month?

**Comment by aleksihakli** [comment]
I added the Read the Docs page and added @kencochrane and @jazzband-bot as the maintainers.

Could you add the GitHub -> Read the Docs webhook integration for the project on the GitHub end @jezdez?

https://readthedocs.org/dashboard/django-defender/integrations/

**Comment by jezdez** [comment]
@aleksihakli Added the webhook.

**Comment by kencochrane** [comment]
Thank you @aleksihakli and @jezdez
