### ISSUE TITLE
Support for redis>=3

### ISSUE THREAD

**Issue by simoncrowe** [jazzband/django-defender#150]
This is a simple request but I don't know how complicated the difference in major version makes it to implement. 

The context is that I was looking at this project as a potential solution for the company I work for and can't use it as we have redis pinned to 3.2.1.

**Comment by kencochrane** [comment]
@simoncrowe it should work fine with Redis 3. If you it, and it didn't work, please let us know what happened so we can fix it.

**Comment by simoncrowe** [comment]
Sorry, now that I look at setup.py, everything should work.  For some reason I got compatibility warnings from pip. I'll have to have another look when I'm back in the office.
