### ISSUE TITLE
Support for Django 3.0

### ISSUE THREAD

**Issue by deeprave** [jazzband/django-defender#151]
Django 3.x has dropped support for python2, and using this module on django 3 is not currently possible due to the (now) undefined django.utils.python_2_unicode_compatible, which needs a workaround so that this function does not get called/referenced when it does not exist.

Since I think this app is handy and don't want to deploy without it, so I will submit a PR if required in the next couple of days when I get a chance to test the changes. But to save on duplicating work I thought I'd raise this in advance just in case someone else has a tested fix. It seems to be relatively straight-forward.

**Comment by kencochrane** [comment]
@deeprave Thank you for the heads up, I don't know of anyone else working on this issue, so if you can submit the PR when it is ready, that would be awesome. Let us know if you have any questions, or need any help.

**Comment by hsenot** [comment]
@deeprave that sounds like a great idea. Just tumbled on the incompatibility today so would definitely welcome a solution. Happy to test it at my end too if needed. Thx for this great project!

**Comment by kencochrane** [comment]
The PR #153 closes this out.

**Comment by kencochrane** [comment]
Version 0.7.0 was just released with these changes.

**Comment by sumanthratna** [comment]
Sorry for commenting on an old thread, but I think the README should be updated. https://github.com/jazzband/django-defender/blob/master/README.rst#requirements says:
> ## Requirements
> - Python: 2.7, 3.5, 3.6, 3.7, 3.8, PyPy
> - Django: 1.11, 2.1, 2.2
> - Redis

This is a really useful package; I was disappointed for a second when I saw that the README said no Django 3 support.

**Comment by kencochrane** [comment]
@sumanthratna I updated the README to include support for Django 3.
