### ISSUE TITLE
Support for other LOGIN_URLs

### ISSUE THREAD

**Issue by muneeba-mughal** [jazzband/django-defender#152]
Hi there! I'm using django-defender in my Django project that also supports two factor authentication and that means my login urls are not default `accounts/login` but the a custom login route `account/login`. 
It would be really nice to have some way to configure login url dynamically with `django-defender` as well. AFAIK, there is no way to configure django-defender this way. IMO, it would be good idea to read the `LOGIN_URL` or `LoginView` variable from the settings to track logins.

Thank you so much for the help in advance.

**Comment by muneeba-mughal** [comment]
Nevermind! I resolved the issue by adding the decorator `watch_login` to my custom view. However adding some documentation is a great idea.

**Comment by muneeba-mughal** [comment]
Nevermind! I resolved the issue by adding the decorator watch_login to my custom view. However adding some documentation is a great idea.

**Comment by kencochrane** [comment]
@muneeba-mughal I'm glad you figured it out, If you can give us an example of how you fixed it, we can add it to the docs. Even better, if you could submit a PR to add it to the docs that would be wonderful.

**Comment by WojciechSzade** [comment]
> Nevermind! I resolved the issue by adding the decorator watch_login to my custom view. However adding some documentation is a great idea.

Hey, could you be so kind and provide more information on how you overcame this issue?  
I am facing the exact same issue using django-two-factor for my authentication and trying to use defender. - it doesn't do anything.  
Have you just overrode the login view from django-two-factor and added that decorator?
