### ISSUE TITLE
support special character in redis password

### ISSUE THREAD

**Issue by calmkart** [jazzband/django-defender#156]
if we have special character in redis password (such like 'calmkart#@!')
we can't urlparse it well.

so i add a new pr #155 
add a param `DEFENDER_REDIS_PASSWORD_QUOTE`
if we have special character in redis password, we can `urllib.quote_plus("password#@!")` it , and set the `DEFENDER_REDIS_PASSWORD_QUOTE` to True.

```
DEFENDER_REDIS_URL = "redis://:password%23%40%21@localhost:6379/0"
DEFENDER_REDIS_PASSWORD_QUOTE = True
```

This will enable support for special characters in redis passwords.

**Comment by kencochrane** [comment]
Closed in #155
