### ISSUE TITLE
always showing localhost django defender

### ISSUE THREAD

**Issue by Hamza-Lachi** [jazzband/django-defender#161]
I deploy my website to ubuntu server with gunicorn and nginx but when I notice the Django defender is always getting 127.0.0.1 IP

and when someone gets blocked the whole website user blocked because only 1 IP address Django defender always getting localhost IP

here is a ScreenShot

![Screenshot from 2020-06-23 02-50-36](https://user-images.githubusercontent.com/53256322/85370513-d403d280-b4fc-11ea-9928-f0e842ec4ae2.png)

there are visitors from different IP but it gets only localhost IP

the problem is Django defender always get localhost IP which is incorrect every user had their own IP

**Comment by kencochrane** [comment]
@Hamza-Lachi do you have NGINX passing along the HTTP_X_FORWARDED_FOR header to your Django app? If you are using a reverse proxy that is where defender will look for the correct address.

Here is an example of the nginx config.

```

server { 
   listen      80; 
   server_name api.mydomain.com;

   charset     utf-8;

   client_max_body_size 1M; 

   location / { 
      set_real_ip_from 127.0.0.1/32;
      proxy_set_header X-Forwarded-Host $host:$server_port;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_pass http://myapi;
   }

   access_log /var/log/nginx/api_access.log;
   error_log  /var/log/nginx/api_error.log;
}
```


Another possible issue is that you might be using a different name for your header, if so you will need to change the name by using the following setting.


DEFENDER_REVERSE_PROXY_HEADER: String: the name of the http header with your reverse proxy IP address [Default: HTTP_X_FORWARDED_FOR]

If that still doesn’t work, post your nginx and django settings, so we can see what might be wrong.

**Comment by Hamza-Lachi** [comment]
I'm also getting the IP from my app 

with this code
`ip = request.META.get('REMOTE_ADDR')`

is this possible to change

DEFENDER_REVERSE_PROXY_HEADER to REMOTE_ADDR

**Comment by kencochrane** [comment]
If you trust that the data in that header is correct, you could change the setting to use it and see if it works for you. If it does, then you should be good to go.

**Comment by Hamza-Lachi** [comment]
sorry that also dosen't work

here is my Nginx settings:

```
server {
    server_name hamza.pawnhost.com;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        root /home/emailv-completed;
    }

    location /media {
     	alias /home/emailv-completed/media;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/emailv-completed/src.sock;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/hamza.pawnhost.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/hamza.pawnhost.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = hamza.pawnhost.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name hamza.pawnhost.com;
    return 404; # managed by Certbot


}
```

**Comment by Hamza-Lachi** [comment]
this is the piece of the code I'm using to get IP

```
def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip
```

and I'm getting IP from that code

why Django defender can't get right IP
I also change `DEFENDER_REVERSE_PROXY_HEADER` to `REMOTE_ADDR` but nothing worked
please help me

**Comment by kencochrane** [comment]
That's weird that you are getting it correctly from code, but not from Defender.

What do you have for the `DEFENDER_BEHIND_REVERSE_PROXY` setting, did you set it to True since you are behind Nginx? If not, go ahead and add that, and see if it works.

Here is the code, which looks similar to yours.
https://github.com/jazzband/django-defender/blob/master/defender/utils.py#L46-L55

```
def get_ip(request):
    """ get the ip address from the request """
    if config.BEHIND_REVERSE_PROXY:
        ip_address = request.META.get(config.REVERSE_PROXY_HEADER, "")
        ip_address = ip_address.split(",", 1)[0].strip()
        if ip_address == "":
            ip_address = get_ip_address_from_request(request)
    else:
        ip_address = get_ip_address_from_request(request)
    return ip_address
```

**Comment by Hamza-Lachi** [comment]
okay it's working after doing this

DEFENDER_BEHIND_REVERSE_PROXY = True
