### ISSUE TITLE
Installation fails if performed in a pipenv

### ISSUE THREAD

**Issue by VentGrey** [jazzband/django-defender#180]
The installation process fails at the migration level, when executing `python manage.py migrate defender` at this point the process fails due to an unexisting module:

```
File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'defendercore'
```

Version: Pypi (Installed using `pipenv install django-defender`), redis is installed as well.

**Comment by kencochrane** [comment]
That is weird, I'm not sure where defendercore is coming from. Can you give more of the stack trace?

**Comment by ethankleinman** [comment]
Double check you have a comma after `defender` in your `settings.INSTALLED_APPS`:
```
INSTALLED_APPS = [
...
'defender',
'core',
...
]
```

**Comment by VentGrey** [comment]
I had it, installed. I ended dropping if in favour of django-axes, sorry for the late response :)
