### ISSUE TITLE
New release scheduled?

### ISSUE THREAD

**Issue by jpsingleton** [jazzband/django-defender#187]
Hi,

I was wondering when a new release was planned? Keen to get the Django 4.0 fix from https://github.com/jazzband/django-defender/issues/184.

Thanks!

**Comment by kencochrane** [comment]
Sorry for the delay the [0.9.1 release](https://pypi.org/project/django-defender/) has been made and now available on pypi.

**Comment by jpsingleton** [comment]
Awesome, thanks.
