### ISSUE TITLE
defender_blocks_view page not found

### ISSUE THREAD

**Issue by satyam-seth** [jazzband/django-defender#190]
<html>
<body>
<div id="summary" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(255, 255, 204); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="padding: 0px; margin: 0px 0px 0.4em; font-weight: normal;">Page not found<span> </span><span style="padding: 0px; margin: 0px; font-size: 15.6px; color: rgb(102, 102, 102); font-weight: normal;">(404)</span></h1>

Request Method: | GET
-- | --
http://127.0.0.1:8000/admin/defender/blocks/
django.contrib.admin.sites.catch_all_view

</div><div id="info" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(246, 246, 246); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="padding: 0px; margin: 0px;">Using the URLconf defined in<span> </span><code style="padding: 0px; margin: 0px;">task.urls</code>, Django tried these URL patterns, in this order:</p><ol style="padding: 0px; margin: 0.5em 4em;"><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/ [name='index']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/ login/ [name='login']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/ logout/ [name='logout']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/ password_change/ [name='password_change']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/ password_change/done/ [name='password_change_done']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/ autocomplete/ [name='autocomplete']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/ jsi18n/ [name='jsi18n']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/ r/&lt;int:content_type_id&gt;/&lt;path:object_id&gt;/ [name='view_on_site']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/ auth/group/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/ auth/user/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/ defender/accessattempt/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/ ^(?P&lt;app_label&gt;auth|defender)/$ [name='app_list']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/ (?P&lt;url&gt;.*)$</li></ol><p style="padding: 0px; margin: 0px;">The current path,<span> </span><code style="padding: 0px; margin: 0px;">admin/defender/blocks/</code>, matched the last one.</p></div>
</body>
</html>

**Comment by rahul-1311** [comment]
i am also facing same issue
