### ISSUE TITLE
New migration is necessary

### ISSUE THREAD

**Issue by panosangelopoulos** [jazzband/django-defender#192]
Hi,

I just noticed a new migration file is necessary for the project.

```
Migrations for 'defender':
  usr/local/lib/python3.7/site-packages/defender/migrations/0002_alter_accessattempt_id.py
    - Alter field id on accessattempt
```

**Comment by wm3ndez** [comment]
Hey @panosangelopoulos — this bug was fixed with PR https://github.com/jazzband/django-defender/pull/197
