### ISSUE TITLE
Missing `AppConfig.default_auto_field` definition

### ISSUE THREAD

**Issue by tbrlpld** [jazzband/django-defender#195]
When using `django-defender` with Django 3.2, I am seeing the following warning being thrown: 

```
$ ./manage.py check
System check identified some issues:

WARNINGS:
defender.AccessAttempt: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
...
```

A possible work around as mentioned in the warning is to define the `DEFAULT_AUTO_FIELD` setting. 

Since this is a library for Django, it would be nice if it does not throw warnings when used with a supported Django version. The fix would be, as mentioned in the warning, to create an `AppConfig` and set the `default_auto_field` attribute. 

This is the related section in the release notes for Django 3.2: https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys

**Comment by kencochrane** [comment]
@tbrlpld Thanks for the heads up. Feel free to submit a PR with your proposed changes and we can review. If they look good and all tests pass, we can merge and push out a new release. Thanks!
