### ISSUE TITLE
Fails to block on IP when X-Forwarded-For includes port information

### ISSUE THREAD

**Issue by ndrsn** [jazzband/django-defender#213]
## Problem

We've set `DEFENDER_BEHIND_REVERSE_PROXY = True`, as well as `DEFENDER_LOCK_OUT_BY_IP_AND_USERNAME = True` to prevent a single user from blocking all the other users from logging in.

But: our application is behind an Azure Application Gateway. This [includes IP port information](https://docs.microsoft.com/en-us/azure/application-gateway/rewrite-http-headers-url#remove-port-information-from-the-x-forwarded-for-header) in the HTTP `X-Forwarded-For` header when sending to the backend. So instead of

```
X-Forwarded-For: 192.168.1.100
```

the header would be

```
X-Forwarded-For: 192.168.1.100:54321
```

This then is recorded in the access attempts. Because the port changes from request to request, and thus the "IP address" appears to be different, the user is not blocked after three failed attempts.

## Possible solutions

1. Have the Application Gateway rewrite the header to drop the port numbers (see link). However, not everyone has permission/access to rewrite the header in Application Gateway.
2. Rewrite the header in a custom Django middleware. While it's usually/mostly (?) `X-Forwarded-For` then you'd have to keep the value of `DEFENDER_REVERSE_PROXY_HEADER` and the header referenced in the middleware in sync
3. Split the IP address in `get_ip`: 
 https://github.com/jazzband/django-defender/blob/45c4575ccd6ded2b8566e96eab27c690f0d0dc6b/defender/utils.py#L50

While options 1 and 2 are obviously possible, I feel option 3 seems fairly simple and risk-free to implement. I can't think of a scenario where _including_ the port number would be of value?

Something like
```python
def clean_ipv46_address(ip_address):
   # implementation follows

ip_address = ip_address.split(",", 1)[0].strip()
ip_address = clean_ipv46_address(ip_address)
```

Would you accept a PR including this change?

--
## Edit

I didn't consider IPv6 addresses, which obviously would make this a little bit less trivial — so implementation still to be worked out

**Comment by kencochrane** [comment]
@ndrsn thanks for reporting this. I agree with your assessment and option 3 seems like the way to go. If you submitted a PR, yes we would accept it. Just make sure you include unit tests for the different use cases (ipv4, ipv6, with and without ports)

It should be pretty easy to determine if the IP is ipv4 or v6, and parse accordingly (https://stackoverflow.com/questions/47738068/regex-for-splitting-ipv4-and-ipv6-ipport-syntax)
