### ISSUE TITLE
Blocked users admin page returns 404

### ISSUE THREAD

**Issue by djmore4** [jazzband/django-defender#226]
@kencochrane so I was working on something to make make this even better at some point in the future and I found that there is another bug unfortunately (thankfully at least it seems completely unrelated to my changes as I can reproduce the behavior when using the current build on PyPi). 

It seems the `Blocked Users` functionality on the defender admin page isn't functioning properly unfortunately
<img width="1475" alt="Screen Shot 2022-11-13 at 12 59 59 PM" src="https://user-images.githubusercontent.com/17936679/201536951-00638be4-2d45-41bd-bfa5-8bd1f6ab0283.png">

_Originally posted by @djmore4 in https://github.com/jazzband/django-defender/issues/223#issuecomment-1312786877_

**Comment by djmore4** [comment]
@kencochrane ^^

**Comment by SyncBAND** [comment]
@djmore4 I also get the same error `path('admin/defender/', include('defender.urls')),` in the urls.py file. But when do add the path, it works as expected. Not sure if you get this error even when you've included the url path already?

<img width="837" alt="Screenshot 2022-11-30 at 04 58 01" src="https://user-images.githubusercontent.com/20128729/204704632-847fb8ac-adfb-4631-b688-a943d8ae578f.png">
<img width="394" alt="Screenshot 2022-11-30 at 04 59 04" src="https://user-images.githubusercontent.com/20128729/204704646-bdf881e9-549a-4ff7-bf94-d1386d512442.png">

**Comment by djmore4** [comment]
@SyncBAND Aha! That wasn't exactly the issue I was having but it was related and I've now solved it so thank you! For context, it appears that there was an ordering issue in my urls.py file so this can be closed. Thanks again, I'll get back to work implementing the cache utilization for the new separated and extended lockout functionality
