### ISSUE TITLE
How to make `django-defender` work with nonunique `username`

### ISSUE THREAD

**Issue by baseplate-admin** [jazzband/django-defender#231]
Hi, Thanks for creating this awesome library.

In my app i allow users to allow creating multiple username differentiated by discriminators ( like discord ). So there can be multiple people with same username. [I join 2 fields using some database magics](https://github.com/baseplate-admin/CoreProject/blob/1ec41c2bf6c88cc19a222825f1b5822c80dc767e/backend/django_core/mixins/manager/username_with_discriminator.py#L12-L33)

now my question is how to add `username_with_discriminator` to `django-defender` `username` field ( or maybe change the unique key from `username` to `email` )

**Comment by kencochrane** [comment]
@baseplate-admin I think this is what you can do.

1. Make a custom function that will get your username with a discriminator from a Request. [similar to the default one](https://github.com/jazzband/django-defender/blob/master/defender/utils.py#LL197C3-L199C16)
2. Change the [`DEFENDER_GET_USERNAME_FROM_REQUEST_PATH`](https://github.com/jazzband/django-defender/blob/master/defender/config.py#L110) settings to reference the custom function in step 1 above.

This might slow down the middleware if you make any database calls in your custom function. This might not be a problem unless you get a ton of logins all the time.

Another thing to remember, you might have people that try to log in but don't have accounts on your site. This happens a lot with bots. Make sure you can handle that use case without throwing 500 errors. just return the original value they entered in the form so you can block them if they try too much.

Good luck!

**Comment by baseplate-admin** [comment]
Thanks a bunch :D
